/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class PINJAM extends javax.swing.JFrame {

    /**
     * Creates new form PINJAM
     */
    public PINJAM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        txtCari1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        txtHariPeminjaman = new javax.swing.JTextField();
        txtBulanPeminjaman = new javax.swing.JTextField();
        txtTahunPeminjaman = new javax.swing.JTextField();
        txtTahunKembali = new javax.swing.JTextField();
        txtBulanKembali = new javax.swing.JTextField();
        txtHariKembali = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBersihkan = new javax.swing.JButton();
        btnMsgDialog = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Pinjam Buku");

        jLabel2.setText("Nama :");

        jLabel3.setText("NIM :");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        txtCari1.setBackground(new java.awt.Color(243, 156, 18));
        txtCari1.setText("Cari");
        txtCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCari1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Judul Buku   :");

        txtJudul.setEditable(false);
        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });

        txtHariPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHariPeminjamanActionPerformed(evt);
            }
        });

        txtBulanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBulanPeminjamanActionPerformed(evt);
            }
        });

        txtBulanKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBulanKembaliActionPerformed(evt);
            }
        });

        txtHariKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHariKembaliActionPerformed(evt);
            }
        });

        btnCek.setBackground(new java.awt.Color(46, 204, 113));
        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("TANGGAL PEMINJAMAN");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("TANGGAL KEMBALI");

        btnBersihkan.setBackground(new java.awt.Color(41, 128, 185));
        btnBersihkan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        btnMsgDialog.setBackground(new java.awt.Color(26, 188, 156));
        btnMsgDialog.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMsgDialog.setText("Simpan");
        btnMsgDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsgDialogActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(232, 67, 147));
        jToggleButton1.setText("Keluar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(232, 67, 147));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama)
                            .addComponent(nim, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHariPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBulanPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtTahunPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCek))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtHariKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBulanKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTahunKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBersihkan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnMsgDialog)))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHariPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBulanPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTahunPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHariKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBulanKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTahunKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBersihkan)))
                .addGap(32, 32, 32)
                .addComponent(btnMsgDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void txtCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCari1ActionPerformed
        String Cari = txtCari.getText();
        switch (Cari){
            case "5916A":
                txtJudul.setText("Animasi Pendidikan Menggunakan Flash");
                break;
                
            case "5196M1":
                txtJudul.setText("Menguasai Efek Khusus dengan Photoshop");
               break;
               
               case "5196G1":
                txtJudul.setText("Grafik dan Animasi Professional Power Point");
               break;
               
               case "5196T1":
                txtJudul.setText("The C++ Programming Language");
               break;
               
               case "5196T11":
                txtJudul.setText("The Magic of Flash MX 2004");
               break;
               
               case "5196F1":
                txtJudul.setText("Foundation Action Script");
               break;
               
               case "5196S1":
                txtJudul.setText("Seluk Beluk Database Relasional");
               break;
               
               default:
                   JOptionPane.showMessageDialog(this, "Buku tidak Ditemukan");
        }
        
    }//GEN-LAST:event_txtCari1ActionPerformed

    private void txtHariPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHariPeminjamanActionPerformed
       
    }//GEN-LAST:event_txtHariPeminjamanActionPerformed

    private void txtBulanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBulanPeminjamanActionPerformed

    }//GEN-LAST:event_txtBulanPeminjamanActionPerformed

    private void txtBulanKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBulanKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBulanKembaliActionPerformed

    private void txtHariKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHariKembaliActionPerformed
        int hari;        // TODO add your handling code here:
    }//GEN-LAST:event_txtHariKembaliActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        int hari = Integer.parseInt(txtHariPeminjaman.getText());
        int bulan = Integer.parseInt(txtBulanPeminjaman.getText());
        int tahun = Integer.parseInt(txtTahunPeminjaman.getText());
        if(hari>23 ){
            if(hari == 24 && bulan ==4){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("5");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==4){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("5");
                txtTahunKembali.setText(tahun+"");
            }if(hari == 26 && bulan ==4){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("5");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==4){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("5");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==4){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("5");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==4){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("5");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==4){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("5");
                txtTahunKembali.setText(tahun+"");
            }

            if(hari == 24 && bulan ==6){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("7");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==6){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("7");
                txtTahunKembali.setText(tahun+"");
            }if(hari == 26 && bulan ==6){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("7");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==6){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("7");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==6){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("7");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==6){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("7");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==6){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("7");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 24 && bulan ==9){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("10");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==9){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("10");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==9){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("10");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==9){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("10");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==9){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("10");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==9){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("10");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==9){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("10");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 24 && bulan ==11){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan==11){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==11){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");

            }
            if(hari == 27 && bulan ==11){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==11){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==11){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan==11){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==1){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("12");
                txtTahunKembali.setText(tahun+"");

            }
            if(hari == 26 && bulan ==1){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("2");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==1){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("2");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==1){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("2");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==1){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("2");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==1){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("2");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 31 && bulan ==1){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("2");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==3){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("4");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==3){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("4");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==3){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("4");
                txtTahunKembali.setText(tahun+"");

            }
            if(hari == 28 && bulan ==3){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("4");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==3){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("4");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==3){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("4");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 31 && bulan ==3){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("4");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==5){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("6");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==5){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("6");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==5){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("6");
                txtTahunKembali.setText(tahun+"");

            }
            if(hari == 28 && bulan ==5){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("6");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==5){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("6");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==5){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("6");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 31 && bulan ==5){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("6");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==7){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("8");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==7){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("8");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==7){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("8");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==7){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("8");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==7){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("8");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==7){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("8");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 31 && bulan ==7){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("8");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==8){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("9");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==8){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("9");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==8){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("9");
                txtTahunKembali.setText(tahun+"");

            }
            if(hari == 28 && bulan ==8){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("9");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==8){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("9");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==8){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("9");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 31 && bulan ==8){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("9");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==10){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("11");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==10){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("11");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==10){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("11");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==10){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("11");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 29 && bulan ==10){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("11");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 30 && bulan ==10){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("11");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 31 && bulan ==10){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("11");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==12){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("1");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==12){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("1");
                txtTahunKembali.setText(tahun+1+"");
            }
            if(hari == 27 && bulan ==12){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("1");
                txtTahunKembali.setText(tahun+1+"");
            }
            if(hari == 28 && bulan ==12){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("1");
                txtTahunKembali.setText(tahun+1+"");
            }
            if(hari == 29 && bulan ==12){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("1");
                txtTahunKembali.setText(tahun+1+"");
            }
            if(hari == 30 && bulan ==12){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("1");
                txtTahunKembali.setText(tahun+1+"");
            }
            if(hari == 31 && bulan ==12){
                txtHariKembali.setText("7");
                txtBulanKembali.setText("1");
                txtTahunKembali.setText(tahun+1+"");
            }
            if(hari == 23 && bulan ==2){
                txtHariKembali.setText("1");
                txtBulanKembali.setText("3");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 24 && bulan ==2){
                txtHariKembali.setText("2");
                txtBulanKembali.setText("3");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 25 && bulan ==2){
                txtHariKembali.setText("3");
                txtBulanKembali.setText("3");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 26 && bulan ==2){
                txtHariKembali.setText("4");
                txtBulanKembali.setText("3");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 27 && bulan ==2){
                txtHariKembali.setText("5");
                txtBulanKembali.setText("3");
                txtTahunKembali.setText(tahun+"");
            }
            if(hari == 28 && bulan ==2){
                txtHariKembali.setText("6");
                txtBulanKembali.setText("3");
                txtTahunKembali.setText(tahun+"");
            }
        }
        else{
            int kembali = hari+7;
            txtHariKembali.setText(kembali+"");
            txtBulanKembali.setText(bulan+"");
            txtTahunKembali.setText(tahun+"");
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        txtJudul.setText("");
        txtHariPeminjaman.setText("");
        txtBulanPeminjaman.setText("");
        txtTahunPeminjaman.setText("");
        txtHariKembali.setText("");
        txtBulanKembali.setText("");
        txtTahunKembali.setText("");
        nama.setText("");
        txtCari.setText("");
        txtJudul.setText("");
        nim.setText("");
        
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void btnMsgDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsgDialogActionPerformed
     JOptionPane.showMessageDialog(this, "Data Anda Telah Tersimpan");
   
    }//GEN-LAST:event_btnMsgDialogActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new PERPUSTAKAANKU().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PINJAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PINJAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PINJAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PINJAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PINJAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnMsgDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField txtBulanKembali;
    private javax.swing.JTextField txtBulanPeminjaman;
    private javax.swing.JTextField txtCari;
    private javax.swing.JButton txtCari1;
    private javax.swing.JTextField txtHariKembali;
    private javax.swing.JTextField txtHariPeminjaman;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtTahunKembali;
    private javax.swing.JTextField txtTahunPeminjaman;
    // End of variables declaration//GEN-END:variables
}
